### ISSUE TITLE
Diego-cell container is not in Ready state 

### ISSUE THREAD

**Issue by dheerajinganti** [SUSE/scf#3477] opened 2020-06-02 17:44 UTC
**Describe the bug**
Diego-cell container stays in Unhealthy state

**To Reproduce**
deploy suse/cf helm chart on k8s based on vmware

**Expected behavior**
Diego-cell-0 to be running in ready state

**Logs**
/var/vcap/sys/log/garden/garden.stdout.log

{"timestamp":"1591117140.747954845","source":"guardian","message":"guardian.create.create-failed-cleaningup.volumizer.image-plugin-destroy.grootfs.delete.groot-deleting.deleting-image.ending","log_level":1,"data":{"cause":"runc run: exit status 1: container_linux.go:346: starting container process caused \"process_linux.go:319: getting the final child's pid from pipe caused \\\"EOF\\\"\"","handle":"rootfs-c-6a6dc1d2-a8ec-48eb-4eba-da507c199002","id":"rootfs-c-6a6dc1d2-a8ec-48eb-4eba-da507c199002","imageID":"rootfs-c-6a6dc1d2-a8ec-48eb-4eba-da507c199002","original_timestamp":"2020-06-02T16:59:00.747725824Z","session":"151.5.2.1","storePath":"/var/vcap/data/grootfs/store/unprivileged"}}
{"timestamp":"1591117140.748028755","source":"guardian","message":"guardian.create.create-failed-cleaningup.volumizer.image-plugin-destroy.grootfs.delete.groot-deleting.ending","log_level":1,"data":{"cause":"runc run: exit status 1: container_linux.go:346: starting container process caused \"process_linux.go:319: getting the final child's pid from pipe caused \\\"EOF\\\"\"","handle":"rootfs-c-6a6dc1d2-a8ec-48eb-4eba-da507c199002","imageID":"rootfs-c-6a6dc1d2-a8ec-48eb-4eba-da507c199002","original_timestamp":"2020-06-02T16:59:00.747789824Z","session":"151.5.2.1"}}
{"timestamp":"1591117140.748051882","source":"guardian","message":"guardian.create.create-failed-cleaningup.volumizer.image-plugin-destroy.grootfs.delete.unused-volumes.starting","log_level":1,"data":{"cause":"runc run: exit status 1: container_linux.go:346: starting container process caused \"process_linux.go:319: getting the final child's pid from pipe caused \\\"EOF\\\"\"","handle":"rootfs-c-6a6dc1d2-a8ec-48eb-4eba-da507c199002","original_timestamp":"2020-06-02T16:59:00.747876608Z","session":"151.5.2.1"}}
{"timestamp":"1591117140.748097897","source":"guardian","message":"guardian.create.create-failed-cleaningup.volumizer.image-plugin-destroy.grootfs.delete.unused-volumes.ending","log_level":1,"data":{"cause":"runc run: exit status 1: container_linux.go:346: starting container process caused \"process_linux.go:319: getting the final child's pid from pipe caused \\\"EOF\\\"\"","handle":"rootfs-c-6a6dc1d2-a8ec-48eb-4eba-da507c199002","original_timestamp":"2020-06-02T16:59:00.74799616Z","session":"151.5.2.1"}}
{"timestamp":"1591117140.765007734","source":"guardian","message":"guardian.create.create-failed-cleaningup.remove-bundle.destroy.started","log_level":1,"data":{"cause":"runc run: exit status 1: container_linux.go:346: starting container process caused \"process_linux.go:319: getting the final child's pid from pipe caused \\\"EOF\\\"\"","handle":"rootfs-c-6a6dc1d2-a8ec-48eb-4eba-da507c199002","session":"151.5.3.1"}}
{"timestamp":"1591117140.765370607","source":"guardian","message":"guardian.create.create-failed-cleaningup.remove-bundle.destroy.finished","log_level":1,"data":{"cause":"runc run: exit status 1: container_linux.go:346: starting container process caused \"process_linux.go:319: getting the final child's pid from pipe caused \\\"EOF\\\"\"","handle":"rootfs-c-6a6dc1d2-a8ec-48eb-4eba-da507c199002","session":"151.5.3.1"}}
{"timestamp":"1591117140.765400410","source":"guardian","message":"guardian.create.create-failed-cleaningup.remove-bundle.destroy.started","log_level":1,"data":{"cause":"runc run: exit status 1: container_linux.go:346: starting container process caused \"process_linux.go:319: getting the final child's pid from pipe caused \\\"EOF\\\"\"","handle":"rootfs-c-6a6dc1d2-a8ec-48eb-4eba-da507c199002","session":"151.5.3.2"}}
{"timestamp":"1591117140.765422106","source":"guardian","message":"guardian.create.create-failed-cleaningup.remove-bundle.destroy.finished","log_level":1,"data":{"cause":"runc run: exit status 1: container_linux.go:346: starting container process caused \"process_linux.go:319: getting the final child's pid from pipe caused \\\"EOF\\\"\"","handle":"rootfs-c-6a6dc1d2-a8ec-48eb-4eba-da507c199002","session":"151.5.3.2"}}
{"timestamp":"1591117140.765436411","source":"guardian","message":"guardian.create.create-failed-cleaningup.cleanedup","log_level":1,"data":{"cause":"runc run: exit status 1: container_linux.go:346: starting container process caused \"process_linux.go:319: getting the final child's pid from pipe caused \\\"EOF\\\"\"","handle":"rootfs-c-6a6dc1d2-a8ec-48eb-4eba-da507c199002","session":"151.5"}}
{"timestamp":"1591117140.765522480","source":"guardian","message":"guardian.api.garden-server.create.failed","log_level":2,"data":{"error":"runc run: exit status 1: container_linux.go:346: starting container process caused \"process_linux.go:319: getting the final child's pid from pipe caused \\\"EOF\\\"\"","request":{"Handle":"rootfs-c-6a6dc1d2-a8ec-48eb-4eba-da507c199002","GraceTime":0,"RootFSPath":"","BindMounts":null,"Network":"","Privileged":false,"Limits":{"bandwidth_limits":{},"cpu_limits":{},"disk_limits":{},"memory_limits":{},"pid_limits":{}}},"session":"3.1.193"}}

**Environment**
 - SCF version
2.20.3
 - Modules enabled
 - Other specifics
set GARDEN_ROOTFS_DRIVER: overlay-xfs
loadbalancer=true

**Additional context**
k8s version: 1.18.3
storage : tried with nfs and vSphere
vSphere : 6.7 update3
container run time: docker://19.3.11
runc version 1.0.0-rc10
     commit: dc9208a3303feef5b3839f4323d9beb36df0a9dd
     spec: 1.0.1-dev
CentOS Linux release 7.6.1810 (Core)

**Comment by jimmykarily** [comment] 2020-06-09 08:23
Hi @dheerajinganti , thank you for reporting this issue. I'm reading this comment: https://github.com/cloudfoundry/garden-runc-release/issues/80 . What is the kernel version on your CentOS?

**Comment by mook-as** [comment] 2020-06-09 16:40
That sounds like https://github.com/cloudfoundry-incubator/kubecf/issues/484 — what is your `user.max_user_namespaces` sysctl setting on your host? It seems like CentOS 7 has it default to 0, which breaks using diego.

**Comment by dheerajinganti** [comment] 2020-06-10 04:45
I am able to fix this issue by upgrading kernel from 3.10 to 4.4.

**Comment by jandubois** [comment] 2020-06-10 18:09
I'm closing this issue; between it likely being a duplicate of #484 and @dheerajinganti having a fix/workaround, there seems to be no action item left for this one. Otherwise please reopen with additional information.

**Closed as completed by jandubois** 2020-06-10 18:09 UTC
