### ISSUE TITLE
Failed to fetch properties through links during pod restart

### ISSUE THREAD

**Issue by zhanggbj** [SUSE/scf#1471] opened 2018-04-23 09:49 UTC
**Background**
api pod will fetch property in cc_uploader by BOSH links, like here. https://github.com/cloudfoundry/capi-release/blob/develop/jobs/cloud_controller_ng/templates/cloud_controller_ng.yml.erb#L360

**Description**
This works well during the first deployment, but when we inject a sidecar container into the api pod, it will trigger a pod recreate, `sometimes` there's one error occurs like below(can't be reproduced 100%).

```
+ bash /opt/fissile/startup/scripts/forward_logfiles.sh
+ configgin --jobs /opt/fissile/job_config.json --env2conf /opt/fissile/env2conf.yml
Resolving link cc_uploader via service {"role"=>"cc-uploader", "job"=>"cc_uploader"}
/usr/local/rvm/gems/ruby-2.3.5/gems/bosh-template-2.0.0/lib/bosh/template/evaluation_link.rb:30:in `p': Can't find property '["internal_hostname"]' (Bosh::Template::UnknownProperty)
	from /var/vcap/jobs-src/cloud_controller_ng/templates/cloud_controller_api.yml.erb:445:in `block in get_binding'
	from /usr/local/rvm/gems/ruby-2.3.5/gems/bosh-template-2.0.0/lib/bosh/template/evaluation_context.rb:152:in `if_link'
	from /var/vcap/jobs-src/cloud_controller_ng/templates/cloud_controller_api.yml.erb:443:in `get_binding'
	from /usr/local/rvm/rubies/ruby-2.3.5/lib/ruby/2.3.0/erb.rb:864:in `eval'
	from /usr/local/rvm/rubies/ruby-2.3.5/lib/ruby/2.3.0/erb.rb:864:in `result'
	from /usr/local/rvm/gems/ruby-2.3.5/gems/configgin-0.14.1/lib/job.rb:57:in `generate'
	from /usr/local/rvm/gems/ruby-2.3.5/gems/configgin-0.14.1/bin/configgin:79:in `block (2 levels) in <top (required)>'
	from /usr/local/rvm/gems/ruby-2.3.5/gems/configgin-0.14.1/bin/configgin:78:in `each'
	from /usr/local/rvm/gems/ruby-2.3.5/gems/configgin-0.14.1/bin/configgin:78:in `block in <top (required)>'
	from /usr/local/rvm/gems/ruby-2.3.5/gems/configgin-0.14.1/bin/configgin:75:in `each'
	from /usr/local/rvm/gems/ruby-2.3.5/gems/configgin-0.14.1/bin/configgin:75:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.3.5/bin/configgin:23:in `load'
	from /usr/local/rvm/gems/ruby-2.3.5/bin/configgin:23:in `<main>'
	from /usr/local/rvm/gems/ruby-2.3.5/bin/ruby_executable_hooks:15:in `eval'
	from /usr/local/rvm/gems/ruby-2.3.5/bin/ruby_executable_hooks:15:in `<main>'
```

These files `job_config.json` and `env2conf.yml` are generated during build time by fissile, right?
So there should be no change for the first deployment and the restart. 

Is there some race issues here?

**Comment by alexjh** [comment] 2018-06-13 22:23
I think I found a way to reproduce this with the UAA while I was testing pr 1595.

I started UAA but immediately scaled down mysql-proxy and mysql:

```
k -n uaa scale statefulset mysql-proxy --replicas=0
k -n uaa scale statefulset mysql --replicas=0
```

Then I scaled up mysql-proxy to `1`. It resulted in the mysql-proxy container hanging while it tried to resolve the link. It didn't go past `Resolving link...` until I scaled up the mysql role.

```
Resolving link mysql via statefulset {"role"=>"mysql", "job"=>"mysql"}

# hung here...

/usr/local/rvm/gems/ruby-2.3.1/gems/configgin-0.15.0/lib/kube_link_generator.rb:166:in `[]': undefined method `[]' for nil:NilClass (NoMethodError)
        from /usr/local/rvm/gems/ruby-2.3.1/gems/bosh-template-2.1.0/lib/bosh/template/property_helper.rb:42:in `block in lookup_property'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/bosh-template-2.1.0/lib/bosh/template/property_helper.rb:41:in `each'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/bosh-template-2.1.0/lib/bosh/template/property_helper.rb:41:in `lookup_property'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/bosh-template-2.1.0/lib/bosh/template/evaluation_context.rb:113:in `link'
        from /var/vcap/jobs-src/proxy/templates/switchboard.yml.erb:2:in `get_binding'
        from /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/erb.rb:864:in `eval'
        from /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/erb.rb:864:in `result'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/configgin-0.15.0/lib/job.rb:70:in `generate'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/configgin-0.15.0/bin/configgin:79:in `block (2 levels) in <top (required)>'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/configgin-0.15.0/bin/configgin:78:in `each'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/configgin-0.15.0/bin/configgin:78:in `block in <top (required)>'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/configgin-0.15.0/bin/configgin:75:in `each'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/configgin-0.15.0/bin/configgin:75:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.3.1/bin/configgin:23:in `load'
        from /usr/local/rvm/gems/ruby-2.3.1/bin/configgin:23:in `<main>'
        from /usr/local/rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
        from /usr/local/rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
```

Definitely looks like a race condition.

**Comment by zhanggbj** [comment] 2018-06-22 08:10
@alexjh yes, this looks very similar to the one I met. Does your pod have 1 container or multi-container? Mostly I encounter this issue in pod with `multi-containers`

**Comment by zhanggbj** [comment] 2018-08-07 06:50
This is fixed. I'll close it.

**Comment by gaktive** [comment] 2018-09-17 18:35
Thanks @zhanggbj, I'll close this issue for now. Let us know if there's anything else.

**Closed by gaktive** 2018-09-17 18:35 UTC
