### ISSUE TITLE
Diego cell memory limits not set

### ISSUE THREAD

**Issue by munzli** [SUSE/scf#1705] opened 2018-08-28 09:08 UTC
***Problem***
Pushing apps will fail while staging because of error 137 (a memory error, afaik).

***Bad Solution***
Setting `DIEGO_CELL_MEMORY_CAPACITY_MB` to a value like `4096` works.

***Detail***
This script https://github.com/SUSE/scf/blob/master/container-host-files/etc/scf/config/scripts/set-diego-cell-memory-limits.sh doesn't work.

total memory is:
```
$ cat /proc/meminfo | awk '/MemTotal:/ { printf "%.0f\n", $2 * 1024 }'
16820776960
```
and:
```
$ cat /sys/fs/cgroup/memory/memory.limit_in_bytes 2>/dev/null || bc <<< '2 ^ 63'
9223372036854771712
```
usually seems to be the highest possible page size (int64).

which means that if `DIEGO_CELL_MEMORY_CAPACITY_MB` is set to `auto` the value will stay unset and staging apps that need to be built usually fails.

***Environment***
- AKS cluster on Azure
- and probably most others aswell

**Comment by gaktive** [comment] 2018-09-06 17:52
Hi,

Thank you for bringing this to our attention. We haven't seen this before so we'll try to reproduce this.

Do you still have the complete error output from the staging process? And any cloud controller logs from that attempt? What type of app were you pushing?

Cheers.

**Comment by mook-as** [comment] 2018-09-13 00:38
So, assuming the script is correct (a very shaky assumption),

When `memory.limit_in_bytes` is `9223372036854771712`, that (probably?) means the container has no memory limit (because `config.memory.limits` isn't set in the helm chart); that means we can go up to the physical memory limit (as shown in `/proc/meminfo`), and diego _should_ be doing the right thing.  So if we're seeing errors starting apps, we _may be_ looking in the wrong spot for the correct memory limit to use.

So it comes down to somebody being able to reproduce this, and then looking around to see what the error actually is, and what limits we should be looking at.

**Comment by munzli** [comment] 2018-09-13 13:44
well, i changed `DIEGO_CELL_MEMORY_CAPACITY_MB` back to `auto` and the error isn't reproducible at the moment (which i find quite strange because it happened about 7 out of 8 times before manually changing the value).
the output while staging was an `exit status 137` at a random point during the process.

what i did:
```bash
# create app
dotnet new mvc -o demonet
zip -r ~/demonet.zip demonet

# push new dotnet demo app 
cf push demonet -p demonet.zip -b https://github.com/cloudfoundry/dotnet-core-buildpack.git
```

i'm not quite sure if you can just set the limit to `/proc/meminfo` because that is the limit of the host/node itself, or am i wrong?

**Comment by mook-as** [comment] 2018-09-13 20:32
`/proc/meminfo` is indeed the limit of the host, which would be a bad idea if the pod has memory limits enabled (because then diego would try to more use memory than it's allowed, and random processes in the container get `SIGKILL`ed).

I'm going to try to reproduce this; do you have any relevant configuration settings (e.g. node size on AKS) I should be aware of? I'm assuming a minimal non-HA setup should be enough.

**Comment by mook-as** [comment] 2018-09-18 00:09
Sorry it took me a while to get a successful AKS deployment (not even the SCF part…)  I seem to have no issues deploying [go-env](https://github.com/mook-as/go-env), on a cluster deployed with `az aks create --resource-group "${NAME}" --name "${NAME}" --node-count 3 --admin-username cf-admin --ssh-key-value … --node-vm-size Standard_D2_v2 --verbose` in `westeurope`.  The SCF/UAA configuration was:
```yaml
config:
  memory:
    limits: false
    requests: false
env:
  DOMAIN: ${NAME}.${DNS_ROOT}
  GARDEN_ROOTFS_DRIVER: overlay-xfs
  TCP_DOMAIN: tcp.${NAME}.${DNS_ROOT}
  UAA_HOST: uaa.${NAME}.${DNS_ROOT}
  UAA_PORT: '2793'
kube:
  auth: rbac
  external_ips: ${private_ips}
  hostpath_available: false
  storage_class:
    persistent: default
secrets:
  CLUSTER_ADMIN_PASSWORD: ${PASSWORD}
  UAA_ADMIN_CLIENT_SECRET: ${SECRET}
services:
  loadbalanced: true
```
The cluster endpoint was configured to use Auzre DNS.

In my `diego-cell`, `/var/vcap/jobs/rep/config/rep.json` contains `"memory_mb": "auto"`.  The `rep` logs say:
```json
{"timestamp":"1537212435.853380203","source":"rep","message":"rep.initial-capacity","log_level":1,"data":{"capacity":{"memory_mb":6969,"disk_mb":20178,"containers":249}}}
```

Relevant files:
`/sys/fs/cgroup/memory/memory.limit_in_bytes` → `9223372036854771712`
`/proc/meminfo` → `MemTotal:        7137152 kB`

I've also managed to deploy the `demonet` sample using `dotnet` SDK 2.1.4 (on openSUSE Leap 15.0).  Note that because I'm using SCF, I needed `-s cflinuxfs2` on your `cf push` command line to select the Ubuntu stack (because the buildpack URL you referenced does not support openSUSE).

I have also deployed with `config.memory.limits: true`, with similar results.

**Comment by munzli** [comment] 2018-09-19 12:31
thanks for taking the time to try and reproduce the error. 👍

unfortunately i didn't check my `rep` logs before i applied the value through the environment variable.
at the moment they say (with the environment variable back to `auto`):
```
{"timestamp":"1537349921.227035284","source":"rep","message":"rep.initial-capacity","log_level":1,"data":{"capacity":{"memory_mb":16041,"disk_mb":109520,"containers":249}}}
```
which seems to be correct if the values are actually used, and like i've mentioned, the error has disappeared.

i still think the `set-diego-cell-memory-limits.sh` script is unnecessary as it is now.

but regarding this issue, i think we can close it, if i run into this problem again i will reopen and make sure to have gathered all the needed logs and versions used.

**Comment by mook-as** [comment] 2018-09-19 16:56
Thanks! I'll close this for now, then, but _please_ do reopen when we can reproduce the issue.

**Closed by mook-as** 2018-09-19 16:56 UTC
