### ISSUE TITLE
diego-cell pod stats cpu memory are all zero

### ISSUE THREAD

**Issue by zhangtbj** [SUSE/scf#1345] opened 2018-02-12 13:38 UTC
When you check the pod status from `kubectl proxy` or kube api ` http://localhost:4194/api/v1.3/docker/`, you can view other pods' cpu and memory normally. But only diego-cell cpu and memory are all empty.

You can see this issue by two ways:

1, in vagrant, `docker ps` and get diego-cell pod container id, then curl http://localhost:4194/api/v1.3/docker/<Container_id>, then you can see all cpu and memory stats are zero

2, view from 'kubectl proxy`:

<img width="658" alt="2018-02-12 9 37 05" src="https://user-images.githubusercontent.com/18108042/36099274-f80fc600-103c-11e8-95b1-6a4eb9cc60ea.png">

**Comment by andrewghobrial** [comment] 2018-02-12 15:46
@zhangtbj  Thanks for looking into this. Actually for me, I am able to see the correct metrics from the cAdvisor (docker) API, but not the heapster (kubernetes) API. I suspect this is an issue with how heapster is collecting the data from cAdvisor

**Comment by zhangtbj** [comment] 2018-02-12 15:51
Hi @andrewghobrial ,

So is there any solution or how to fix it?

Thanks!

**Comment by zhangtbj** [comment] 2018-02-13 01:38
Hi @andrewghobrial , so you only try to solve how to show in cAdvisor?

Will you fix the issue in heapster? because we always use `kube proxy` to check pod status.

Thanks!

**Comment by andrewghobrial** [comment] 2018-02-13 01:51
@zhangtbj I don't know how to fix it in heapster. I don't think we should be using data from cadvisor directly.

**Comment by mook-as** [comment] 2018-02-23 01:55
Hi guys! Thanks for filing this.

To help future-me figure out what the issue is: the relevant info is reachable via jq:
`curl http://localhost:4194/api/v1.3/docker/ | jq -Cc '. | to_entries | .[].value | select(.labels.role == "diego-cell") | .stats[].memory'`
(This is more a note to myself to figure out how to reproduce the issue, first.)

And to confirm, yes docker seems to be able to get the relevant stats:
`docker stats | grep $(docker ps | awk '/k8s_diego-cell/ { print $1 }')`
(This is on a the vagrant box, so running docker gets us _something_, though it wouldn't scale to actual deployments.)

However, I seem to be able to see the stats from the kubernetes dashboard:
![Kubernetes dashboard showing CPU/memory stats for diego-cell-0](https://user-images.githubusercontent.com/3977982/36573967-2e578dc0-17f8-11e8-8746-d49d3f5cb123.png)

More notes for myself, for future debugging:
To get the correct view on the vagrant box:
1. Edit `/etc/kubernetes/kubelet`:
    - Set `KUBELET_ADDRESS` to `0.0.0.0` so it is reachable from the heapster container
    - Set the hostname override to `KUBELET_HOSTNAME="--hostname-override=192.168.77.77"` so it stops reporting itself as `127.0.0.1`
    - `vagrant reload` to apply changes
    - Remember to delete the obsolete node
2. Install heapster via helm charts:
    - https://github.com/kubernetes/heapster/tree/master/deploy/kube-config/influxdb
    - https://github.com/kubernetes/heapster/tree/master/deploy/kube-config/rbac
3. Install the dashboard
    - `kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml`
    - `k edit svc :dash` to type `NodePort`
4. Access the dashboard at `https://cf-dev.io:<dashboard service port>`

**Comment by mook-as** [comment] 2018-02-23 23:23
FWIW, cAdvisor appears to be getting memory stats here too. Which is odd, because that curl line above…
![cAdvisor screen capture showing CPU and memory usage](https://user-images.githubusercontent.com/3977982/36620824-c101ace4-18a9-11e8-8238-a0208383330a.png)

It looks like cAdvisor asks for `/api/v1.3/subcontainers/kubepods/besteffort/pod8acae59a-18e5-11e8-b613-e83935273f68/4e18770d8e492b2de08c7d622f8ba80368d97d8f6c07057985f1ea9ce8bb1e73` which returns multiple things; the relevant ones seem to be:
- `/kubepods/besteffort/pod8acae59a-18e5-11e8-b613-e83935273f68/4e18770d8e492b2de08c7d622f8ba80368d97d8f6c07057985f1ea9ce8bb1e73`
- `/kubepods/besteffort/pod8acae59a-18e5-11e8-b613-e83935273f68/4e18770d8e492b2de08c7d622f8ba80368d97d8f6c07057985f1ea9ce8bb1e73/kubepods/besteffort/pod8acae59a-18e5-11e8-b613-e83935273f68/4e18770d8e492b2de08c7d622f8ba80368d97d8f6c07057985f1ea9ce8bb1e73`

Yes, the second one has the whole thing doubled up. But the _first_ one has the stats.

For me, `/docker/4e18770d8e492b2de08c7d622f8ba80368d97d8f6c07057985f1ea9ce8bb1e73` returns `/kubepods/besteffort/pod8acae59a-18e5-11e8-b613-e83935273f68/4e18770d8e492b2de08c7d622f8ba80368d97d8f6c07057985f1ea9ce8bb1e73/kubepods/besteffort/pod8acae59a-18e5-11e8-b613-e83935273f68/4e18770d8e492b2de08c7d622f8ba80368d97d8f6c07057985f1ea9ce8bb1e73` (the one without the stats).  That appears to match your results.

**Comment by mook-as** [comment] 2018-02-26 19:14
Pending more investigation, but it looks like when guardian [creates cgroup paths](https://github.com/cloudfoundry/guardian/blob/7446753e3fbfe713199d5c6c976a999d119d5433/rundmc/cgroups/starter_linux.go#L192), it's getting the absolute path:
```json
{"timestamp":"1519423537.751707792","source":"guardian-setup","message":"guardian-setup.creating-garden-cgroup.started", "log_level":1,"data":{"gardenCgroup":"/sys/fs/cgroup/cpu/kubepods/besteffort/pod8acae59a-18e5-11e8-b613-e83935273f68/4e18770d8e492b2de08c7d622f8ba80368d97d8f6c07057985f1ea9ce8bb1e73/garden","session":"4"}}
```
However, it's actually *inside* a namespace, so when it tries to create that directory, it ends up creating one that (when viewed from the root namespace) is nested.  This appears to confuse the heck out of everybody, and we (sometimes) get nonsensical results.

This is because [`/proc/self/cgroup`](https://github.com/cloudfoundry/guardian/blob/7446753e3fbfe713199d5c6c976a999d119d5433/guardiancmd/command_linux.go#L121) has the root-relative paths in it (e.g. `/kubepods/besteffort/pod8acae59a-18e5-11e8-b613-e83935273f68/4e18770d8e492b2de08c7d622f8ba80368d97d8f6c07057985f1ea9ce8bb1e73`).  Looks like this is moby/moby#34584; that also points out that `/proc/self/mountinfo` has the mount information we need to fix it.

**Comment by zhangtbj** [comment] 2018-02-27 01:38
Glad to see you can find some issue. Actually, we have multiple diego-cell, but only one diego-cell has some metrics, others are empty. We didn't find the different between them right now. Thanks!

**Comment by Xiaohua-Shen** [comment] 2018-02-27 06:06
we have 6 cells, and only 1 cell's stats can be viewed in kubernetes dashboard.
<img width="1325" alt="2018-02-26 4 39 18" src="https://user-images.githubusercontent.com/19463092/36712252-e871b816-1bc2-11e8-96de-6f49700b643f.png">

for `curl http://localhost:4194/api/v1.3/docker/ | jq -Cc '. | to_entries | .[].value | select(.labels.role == "diego-cell") | .stats[].memory'`   all 6 cells has usage `zero`

seems kubernetes dashboard's metrics is not comes from `http://localhost:4194/api/v1.3/docker/`, because diego-cell-3 has stats on dashboard but has usage `zero` from this cadvisor api.

for `curl http://localhost:4194/api/v1.3/subcontainers/ | jq -Cc '. | to_entries | .[].value | select(.labels.role == "diego-cell") | .stats[].memory'` all 6 cells has similar output:  

name as `/kubepods/besteffort/pod50f918ef-f2c7-11e7-a72c-965343370954/7a230862fdb7105486823868cf2e8f3d5a4
ba1954f46e62d3b52e48529003666/kubepods/besteffort/pod50f918ef-f2c7-11e7-a72c-965343370954/7a230862fdb7105486823868cf2e8f3d5a4ba1954f46e62d3b52e48529003666` has no metrics .

name as `/kubepods/besteffort/pod50f918ef-f2c7-11e7-a72c-965343370954/7a230862fdb7105486823868cf2e8f3d5a4
ba1954f46e62d3b52e48529003666`  has metrics.

**Comment by mook-as** [comment] 2018-02-28 02:31
Yep, as far as I can tell the APIs return cgroups in undefined order, so heapster (cadvisor? dashboard? _somebody_ in that chain) just picks one at random. If you're lucky, you get the actual docker cgroup, and the metrics work fine. If you get unlucky, it picks one of the other ones (I've seen multiple), and it just reports nothing.

Would you folks be able to test out the changes in https://github.com/cloudfoundry/guardian/compare/master...mook-as:cgroup-nested-create to see if that helps?  If it does, I'll look at figuring out how to run all the upstream tests so I can make a PR. Thanks!

**Comment by Xiaohua-Shen** [comment] 2018-03-03 07:38
@mook-as the change seems work. After add this fix:

`curl http://localhost:4194/api/v1.3/subcontainers/ | jq -Cc '. | to_entries | .[].value | select(.labels.role == "diego-cell") | .stats[].memory'` only return `/kubepods/besteffort/pod50f918ef-f2c7-11e7-a72c-965343370954/7a230862fdb7105486823868cf2e8f3d5a4 ba1954f46e62d3b52e48529003666` related metrics, and they are not zero.

**Comment by mook-as** [comment] 2018-03-22 22:27
Testing out the garden suggestion of a volume mount works; the change is something like
```yaml
        volumeMounts:
        - mountPath: /sys/fs/cgroup
          name: cgroup
          readOnly: false
      volumes:
      - name: cgroup
        hostPath:
          path: /sys/fs/cgroup
          type: Directory
```
Obviously, this only works if hostpath is allowed.

This might tie well together with SUSE/fissile#340 as well (sharing between containers).

**Comment by alexjh** [comment] 2018-04-30 22:34
Merged https://github.com/SUSE/scf/pull/1475 to fix this issue.

**Closed by alexjh** 2018-04-30 22:34 UTC
